version: '1'

services:
  db:
    image: khaller/graphdb-free
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  graphdb-data: